# Generated by Django 4.2.30 on 2026-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge_images/'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=models.TextField(verbose_name='投稿内容'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
